const INIT_START_UP_TASKS_SAGA = 'app/startup/INIT_START_UP_TASKS_SAGA';
const SET_STARTUP_COMPLETED = 'app/startup/SET_STARTUP_COMPLETED';

export {
  INIT_START_UP_TASKS_SAGA,
  SET_STARTUP_COMPLETED,
};
